# Cartola FC API

In [86]:
import pandas as pd
import requests
import json
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

## Dados API Cartola FC

In [87]:
url      = 'https://api.cartola.globo.com/atletas/pontuados/6'
resposta = requests.request("GET", url)
objetos  = json.loads(resposta.text)

In [88]:
objetos.keys()

dict_keys(['atletas', 'clubes', 'posicoes', 'rodada', 'total_atletas'])

In [89]:
objetos['atletas']['100079']

{'scout': {'DS': 8, 'FS': 3},
 'apelido': 'Zaracho',
 'foto': 'https://s.sde.globo.com/media/person_role/2023/03/01/photo_FORMATO_d4nyoPf.png',
 'pontuacao': 11.1,
 'posicao_id': 4,
 'clube_id': 282,
 'entrou_em_campo': True}

In [90]:
pd.json_normalize(objetos['atletas'].values()).head(3)

,apelido,foto,pontuacao,posicao_id,clube_id,entrou_em_campo,scout.DS,scout.FS,scout.CA,scout.FC,...,scout.SG,scout.I,scout.A,scout.FT,scout.DE,scout.GS,scout.PS,scout.V,scout.PC,scout.CV
0,Zaracho,https://s.sde.globo.com/media/person_role/2023...,11.1,4,282,True,8.0,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Igor Gomes,https://s.sde.globo.com/media/person_role/2023...,0.0,4,282,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Luis Segovia,https://s.sde.globo.com/media/person_role/2023...,-0.8,3,263,True,NaN,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
url      = 'https://api.cartola.globo.com/partidas/6'
resposta = requests.request("GET", url)
objetos  = json.loads(resposta.text)

In [92]:
objetos.keys()

dict_keys(['clubes', 'partidas', 'rodada'])

In [93]:
objetos['partidas'][0]

{'aproveitamento_visitante': ['d', 'd', 'd', 'v', 'v'],
 'aproveitamento_mandante': ['d', 'v', 'v', 'd', 'd'],
 'transmissao': {'label': 'veja como foi',
  'url': 'https://ge.globo.com/ba/futebol/brasileirao-serie-a/jogo/13-05-2023/bahia-flamengo.ghtml?utm_source=cartolafc'},
 'local': 'Itaipava Arena Fonte Nova',
 'status_transmissao_tr': '',
 'status_cronometro_tr': '',
 'periodo_tr': '',
 'partida_data': '2023-05-13 16:00:00',
 'inicio_cronometro_tr': '',
 'placar_oficial_visitante': 3,
 'placar_oficial_mandante': 2,
 'partida_id': 302699,
 'clube_visitante_posicao': 9,
 'clube_visitante_id': 262,
 'clube_casa_posicao': 14,
 'clube_casa_id': 265,
 'timestamp': 1684004400,
 'campeonato_id': 26,
 'valida': True}

In [94]:
pd.json_normalize(objetos['partidas']).head(3)

,aproveitamento_visitante,aproveitamento_mandante,local,status_transmissao_tr,status_cronometro_tr,periodo_tr,partida_data,inicio_cronometro_tr,placar_oficial_visitante,placar_oficial_mandante,partida_id,clube_visitante_posicao,clube_visitante_id,clube_casa_posicao,clube_casa_id,timestamp,campeonato_id,valida,transmissao.label,transmissao.url
0,"[d, d, d, v, v]","[d, v, v, d, d]",Itaipava Arena Fonte Nova,,,,2023-05-13 16:00:00,,3,2,302699,9,262,14,265,1684004400,26,True,veja como foi,https://ge.globo.com/ba/futebol/brasileirao-se...
1,"[e, d, v, d, d]","[v, d, e, v, v]",MaracanÃ£,,,,2023-05-13 18:30:00,,0,2,302691,18,1371,3,266,1684013400,26,True,veja como foi,https://ge.globo.com/rj/futebol/brasileirao-se...
2,"[e, d, e, e, e]","[e, v, v, v, e]",Allianz Parque,,,,2023-05-13 18:30:00,,1,1,302693,13,280,2,275,1684013400,26,True,veja como foi,https://ge.globo.com/sp/futebol/brasileirao-se...

In [95]:
url        = 'https://api.cartola.globo.com/atletas/mercado'
resposta   = requests.request("GET", url)
objetos    = json.loads(resposta.text)

In [96]:
objetos.keys()

dict_keys(['clubes', 'posicoes', 'status', 'atletas'])

In [97]:
pd.json_normalize(objetos['clubes'].values()).head(3)

,id,nome,abreviacao,nome_fantasia,escudos.60x60,escudos.45x45,escudos.30x30
0,1371,CuiabÃ¡,CUI,CuiabÃ¡,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...
1,262,Flamengo,FLA,Flamengo,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...
2,263,Botafogo,BOT,Botafogo,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...

In [98]:
pd.json_normalize(objetos['posicoes'].values()).head(3)

   id      nome abreviacao
0   1   Goleiro        gol
1   2   Lateral        lat
2   3  Zagueiro        zag

In [99]:
pd.json_normalize(objetos['status'].values()).head(3)

         nome  id
0      DÃºvida   2
1    Suspenso   3
2  Contundido   5

In [100]:
pd.json_normalize(objetos['atletas']).head(3)

,atleta_id,rodada_id,clube_id,posicao_id,status_id,pontos_num,preco_num,variacao_num,media_num,jogos_num,...,gato_mestre.scouts.mandante.DP,scout.PP,gato_mestre.scouts.media.PP,gato_mestre.scouts.mandante.PP,scout.GC,gato_mestre.scouts.media.GC,gato_mestre.scouts.mandante.GC,gato_mestre.scouts.visitante.PP,gato_mestre.scouts.visitante.GC,gato_mestre.scouts.visitante.DP
0,81845,6,276,4,7,0.0,4.53,-0.62,2.53,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,72372,6,276,1,6,0.0,6.00,0.00,0.00,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,110415,6,277,5,7,2.7,7.01,-1.01,5.15,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## PontuaÃ§Ã£o Cartola FC

In [101]:
scout = ['G','A','FT','FD','FF','FS','PS','PP','I',
         'SG','DP','DE','DS','GC','CV','CA','GS','FC','PC']

scout_desc = ['Gol','AssistÃªncia','FinalizaÃ§Ã£o na trave',
              'FinalizaÃ§Ã£o defendida','FInalizaÃ§Ã£o para fora',
              'Falta sofrida','PÃªnalti sofrido','PÃªnalti perdido',
              'Impedimento',
              'Jogo sem sofrer gols (somente defensores pontuam)',
              'Defesa de pÃªnalti','Defesa*','Desarme','Gol contra',
              'CartÃ£o vermelho','CartÃ£o amarelo','Gol sofrido',
              'Falta cometida','PÃªnalti cometido']

scout_pontos = [8,5,3,1.2,0.8,0.5,1,-4,-0.1,5
                ,7,1,1.2,-3,-3,-1,-1,-0.3,-1]

scout_tipo = ['Ataque','Ataque','Ataque','Ataque','Ataque',
              'Ataque','Ataque','Ataque','Ataque',
              'Defesa','Defesa','Defesa','Defesa','Defesa',
              'Defesa','Defesa','Defesa','Defesa','Defesa']

scout_var = ['Positivo','Positivo','Positivo','Positivo',
             'Positivo','Positivo','Positivo','Negativo',
             'Negativo','Positivo','Positivo',
             'Positivo','Positivo','Negativo','Negativo',
             'Negativo','Negativo','Negativo','Negativo']

In [102]:
dic_scout = {
    'scout' : scout,
    'scout_desc' : scout_desc,
    'scout_pontos' : scout_pontos,
    'scout_tipo' : scout_tipo,
    'scout_var' : scout_var,
}

In [103]:
df_scout = pd.DataFrame(dic_scout)
df_scout

,scout,scout_desc,scout_pontos,scout_tipo,scout_var
0,G,Gol,8.0,Ataque,Positivo
1,A,AssistÃªncia,5.0,Ataque,Positivo
2,FT,FinalizaÃ§Ã£o na trave,3.0,Ataque,Positivo
3,FD,FinalizaÃ§Ã£o defendida,1.2,Ataque,Positivo
4,FF,FInalizaÃ§Ã£o para fora,0.8,Ataque,Positivo
5,FS,Falta sofrida,0.5,Ataque,Positivo
6,PS,PÃªnalti sofrido,1.0,Ataque,Positivo
7,PP,PÃªnalti perdido,-4.0,Ataque,Negativo
8,I,Impedimento,-0.1,Ataque,Negativo
9,SG,Jogo sem sofrer gols (somente defensores pontuam),5.0,Defesa,Positivo
10,DP,Defesa de pÃªnalti,7.0,Defesa,Positivo
11,DE,Defesa*,1.0,Defesa,Positivo
12,DS,Desarme,1.2,Defesa,Positivo
13,GC,Gol contra,-3.0,Defesa,Negativo
14,CV,CartÃ£o vermelho,-3.0,Defesa,Negativo
15,CA,CartÃ£o amarelo,-1.0,Defesa,Negativo
16,GS,Gol sofrido,-1.0,Defesa,Negativo
17,FC,Falta cometida,-0.3,Defesa,Negativo
18,PC,PÃªnalti cometido,-1.0,Defesa,Negativo

## Jogadores PontuaÃ§Ã£o

In [104]:
atual_rodada = 6

In [105]:
def get_dados(rodada):
  # RequisiÃ§Ã£o dos dados
  url        = 'https://api.cartola.globo.com/atletas/pontuados/'+ str(rodada)
  parametros = {}
  resposta   = requests.request("GET", url, params=parametros)
  try:
    objetos  = json.loads(resposta.text)
    return objetos
  except:
    return print('Erro rodada {}'.format(rodada))

In [106]:
scouts_rodada = []
for r in range(atual_rodada):
  scouts_rodada.append(get_dados(r+1))

In [107]:
scouts_rodada[0].keys()

dict_keys(['atletas', 'clubes', 'posicoes', 'rodada', 'total_atletas'])

In [108]:
def get_partida(rodada):
  # RequisiÃ§Ã£o dos dados
  url        = 'https://api.cartola.globo.com/partidas/'+ str(rodada)
  parametros = {}
  resposta   = requests.request("GET", url, params=parametros)
  try:
    objetos  = json.loads(resposta.text)
    return objetos
  except:
    return print('Erro rodada {}'.format(rodada))

In [109]:
partida_rodada = []
for r in range(atual_rodada+1):
  partida_rodada.append(get_partida(r+1))

In [110]:
#partida_rodada[2].keys()

In [111]:
#partida_rodada[2]

In [112]:
def get_rodadas(rodada):
  df_rodadas = pd.json_normalize(partida_rodada[rodada]['partidas'])
  df_rodadas['rodada_id'] = partida_rodada[rodada]['rodada']
  df_clubes_ro = pd.json_normalize(partida_rodada[rodada]['clubes'].values())
  df_clubes_ro.rename(columns={'abreviacao': 'clube_visitante', 'id':'clube_visitante_id'}, inplace=True)
  df_rodadas = df_rodadas.join(df_clubes_ro[['clube_visitante_id','clube_visitante']].set_index('clube_visitante_id'), on='clube_visitante_id')
  df_clubes_ro = pd.json_normalize(partida_rodada[rodada]['clubes'].values())
  df_clubes_ro.rename(columns={'abreviacao': 'clube_casa', 'id':'clube_casa_id'}, inplace=True)
  df_rodadas = df_rodadas.join(df_clubes_ro[['clube_casa_id','clube_casa']].set_index('clube_casa_id'), on='clube_casa_id')
  return df_rodadas[['rodada_id','clube_casa_id','clube_casa','clube_visitante_id','clube_visitante']]

In [113]:
df_rodadas_full = pd.DataFrame()
for r in range(atual_rodada+1):
  df_temp_ro = get_rodadas(r)
  df_rodadas_full = pd.concat([df_rodadas_full, df_temp_ro], ignore_index=True, sort=False)

In [114]:
df_rodadas_full.query('rodada_id == 6')

    rodada_id  clube_casa_id clube_casa  clube_visitante_id clube_visitante
10          2            266        FLU                 293             CAP
11          2            276        SAO                 327             AME
12          2           1371        CUI                 280             BGT
13          2            283        CRU                 284             GRE
14          2            285        INT                 262             FLA
15          2            267        VAS                 275             PAL
16          2            277        SAN                 282             CAM
17          2            294        CFC                 356             FOR
18          2            290        GOI                 264             COR
19          2            265        BAH                 263             BOT

### Atletas

In [115]:
def get_scouts(rodada):
  df_scouts = pd.json_normalize(scouts_rodada[rodada]['atletas'].values())
  df_scouts['atleta_id'] = scouts_rodada[rodada]['atletas'].keys()
  df_scouts['atleta_id'] = df_scouts['atleta_id'].apply(int)
  df_scouts['rodada_id'] = scouts_rodada[rodada]['rodada']
  df_scouts.drop(columns=['apelido', 'foto', 'pontuacao', 'posicao_id', 'clube_id', 'entrou_em_campo'], inplace=True)
  df_scouts.head(2)

  list_scouts = [s for s in df_scouts.columns if 'scout' in s]
  dict_scouts = {s : s.split('.')[1] for s in list_scouts}
  df_scouts.rename(columns=dict_scouts, inplace=True)

  list_scouts_dif = list(set(list(dict_scouts.values())).symmetric_difference(set(list(df_scout['scout']))))
  for c in list_scouts_dif:
    df_scouts[c] = 0.0

  df_scouts.fillna(0.0, inplace=True)
  return df_scouts

In [116]:
columns_full = ['G', 'A', 'FT', 'FD', 'FF', 'FS', 'PS', 'PP', 'I',
                'SG', 'DP', 'DE', 'DS', 'GC', 'CV', 'CA',
                'GS', 'FC', 'PC','atleta_id', 'rodada_id']
df_scouts_full = pd.DataFrame()
for r in range(atual_rodada):
  df_temp = get_scouts(r)
  df_scouts_full = pd.concat([df_scouts_full, df_temp[columns_full]], ignore_index=True, sort=False)

In [157]:
df_scouts_full.query('atleta_id == 100079')

,G,A,FT,FD,FF,FS,PS,PP,I,SG,...,DE,DS,GC,CV,CA,GS,FC,PC,atleta_id,rodada_id
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,3.0,0.0,100079,1
337,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,100079,2
671,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,100079,3
1009,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,100079,4
1344,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,0.0,1.0,0.0,3.0,0.0,100079,5
1682,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,100079,6

## Mercado

In [118]:
# RequisiÃ§Ã£o dos dados
url        = 'https://api.cartola.globo.com/atletas/mercado'
parametros = {}
resposta   = requests.request("GET", url, params=parametros)
objetos    = json.loads(resposta.text)

In [119]:
objetos.keys()

dict_keys(['clubes', 'posicoes', 'status', 'atletas'])

In [120]:
objetos['status']

{'2': {'nome': 'DÃºvida', 'id': 2},
 '3': {'nome': 'Suspenso', 'id': 3},
 '5': {'nome': 'Contundido', 'id': 5},
 '6': {'nome': 'Nulo', 'id': 6},
 '7': {'nome': 'ProvÃ¡vel', 'id': 7}}

### Clubes

In [121]:
df_clubes_mer = pd.json_normalize(objetos['clubes'].values())
df_clubes_mer.rename(columns={'abreviacao': 'clube', 'id':'clube_id'}, inplace=True)
df_clubes_mer.head(2)

,clube_id,nome,clube,nome_fantasia,escudos.60x60,escudos.45x45,escudos.30x30
0,1371,CuiabÃ¡,CUI,CuiabÃ¡,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...
1,262,Flamengo,FLA,Flamengo,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...

### PosiÃ§Ãµes

In [122]:
df_posicoes_mer = pd.json_normalize(objetos['posicoes'].values())
df_posicoes_mer.rename(columns={'abreviacao': 'posicao', 'id':'posicao_id'}, inplace=True)
df_posicoes_mer.head(2)

   posicao_id     nome posicao
0           1  Goleiro     gol
1           2  Lateral     lat

### Status

In [123]:
df_status_mer = pd.json_normalize(objetos['status'].values())
df_status_mer.rename(columns={'nome': 'status', 'id':'status_id'}, inplace=True)
df_status_mer

       status  status_id
0      DÃºvida          2
1    Suspenso          3
2  Contundido          5
3        Nulo          6
4    ProvÃ¡vel          7

### Atleta

In [124]:
df_atletas_mer = pd.DataFrame(objetos['atletas'])
df_atletas_mer.drop(columns=['foto'],inplace=True)
df_atletas_mer.head(2)

,scout,atleta_id,rodada_id,clube_id,posicao_id,status_id,pontos_num,preco_num,variacao_num,media_num,jogos_num,minimo_para_valorizar,gato_mestre,slug,apelido,apelido_abreviado,nome
0,"{'A': 1, 'CA': 1, 'DS': 6, 'FC': 5, 'FD': 1, '...",81845,6,276,4,7,0.0,4.53,-0.62,2.53,6,0.18,"{'media_pontos_mandante': 3.35, 'media_pontos_...",alisson,Alisson,Alisson,Alisson Euler de Freitas Castro
1,{},72372,6,276,1,6,0.0,6.00,0.00,0.00,0,6.78,"{'media_pontos_mandante': None, 'media_pontos_...",felipe-alves,Felipe Alves,F. Alves,Felipe Alves Raymundo

### Atleta Completo Mercado

In [125]:
df_atletas_mer_full = df_atletas_mer.join(df_clubes_mer[['clube_id','clube']].set_index('clube_id'), on='clube_id')
df_atletas_mer_full = df_atletas_mer_full.join(df_posicoes_mer[['posicao_id','posicao']].set_index('posicao_id'), on='posicao_id')
df_atletas_mer_full = df_atletas_mer_full.join(df_status_mer[['status_id','status']].set_index('status_id'), on='status_id')
df_atletas_mer_full.head(2)

,scout,atleta_id,rodada_id,clube_id,posicao_id,status_id,pontos_num,preco_num,variacao_num,media_num,jogos_num,minimo_para_valorizar,gato_mestre,slug,apelido,apelido_abreviado,nome,clube,posicao,status
0,"{'A': 1, 'CA': 1, 'DS': 6, 'FC': 5, 'FD': 1, '...",81845,6,276,4,7,0.0,4.53,-0.62,2.53,6,0.18,"{'media_pontos_mandante': 3.35, 'media_pontos_...",alisson,Alisson,Alisson,Alisson Euler de Freitas Castro,SAO,mei,ProvÃ¡vel
1,{},72372,6,276,1,6,0.0,6.00,0.00,0.00,0,6.78,"{'media_pontos_mandante': None, 'media_pontos_...",felipe-alves,Felipe Alves,F. Alves,Felipe Alves Raymundo,SAO,gol,Nulo

## Mercado com PontuaÃ§Ã£o

In [126]:
df_atletas_full = df_atletas_mer_full.drop(columns=['rodada_id']).join(df_scouts_full.set_index('atleta_id'), on='atleta_id', how='inner')

In [127]:
df_rodadas_full_casa  = df_rodadas_full.rename(columns={'clube_casa_id': 'clube_id','clube_visitante_id': 'clube_adversario_id','clube_visitante': 'clube_adversario'})
df_rodadas_full_visi  = df_rodadas_full.rename(columns={'clube_visitante_id': 'clube_id','clube_casa_id': 'clube_adversario_id','clube_casa': 'clube_adversario'})

In [128]:
df_atletas_full = pd.merge(df_atletas_full, df_rodadas_full_casa,  how='left', left_on=['clube_id','rodada_id'], right_on = ['clube_id','rodada_id'])
df_atletas_full = pd.merge(df_atletas_full, df_rodadas_full_visi,  how='left', left_on=['clube_id','rodada_id'], right_on = ['clube_id','rodada_id'])
df_atletas_full['clube_adversario_id'] = df_atletas_full.clube_adversario_id_x.combine_first(df_atletas_full.clube_adversario_id_y)
df_atletas_full['clube_adversario_id'] = df_atletas_full['clube_adversario_id'].apply(int)
df_atletas_full['clube_adversario'] = df_atletas_full.clube_adversario_x.combine_first(df_atletas_full.clube_adversario_y)

In [129]:
df_atletas_full.columns

Index(['scout', 'atleta_id', 'clube_id', 'posicao_id', 'status_id',
       'pontos_num', 'preco_num', 'variacao_num', 'media_num', 'jogos_num',
       'minimo_para_valorizar', 'gato_mestre', 'slug', 'apelido',
       'apelido_abreviado', 'nome', 'clube', 'posicao', 'status', 'G', 'A',
       'FT', 'FD', 'FF', 'FS', 'PS', 'PP', 'I', 'SG', 'DP', 'DE', 'DS', 'GC',
       'CV', 'CA', 'GS', 'FC', 'PC', 'rodada_id', 'clube_casa',
       'clube_adversario_id_x', 'clube_adversario_x', 'clube_adversario_id_y',
       'clube_adversario_y', 'clube_visitante', 'clube_adversario_id',
       'clube_adversario'],
      dtype='object')

In [130]:
select_columns = ['rodada_id', 'pontos_num', 'preco_num', 'variacao_num', 
                  'media_num', 'jogos_num', 'minimo_para_valorizar', 
                  'apelido', 'clube_id', 'clube', 'posicao', 'status', 'DS','FC', 
                  'FS', 'I', 'A', 'FD', 'FF', 'CA', 'G', 'FT', 
                  'SG','DE', 'GS', 'PS','PC', 'CV', 'GC', 'DP', 'PP', 
                  'clube_adversario_id','clube_adversario']
df = df_atletas_full[select_columns].copy()

## AnÃ¡lise dos Dados

In [131]:
df['scout_ataque'] = df['G']*8.0 + df['A']*5.0 + df['FT']*3.0 + df['FD']*1.2 + \
                    df['FF']*0.8 + df['FS']*0.5 + df['PS']*1.0 + df['PP']*-4.0 + \
                    df['I']*-0.1

df['scout_defesa'] = df['SG']*5.0 + df['DP']*7.0 + \
                    df['DE']*1.0 + df['DS']*1.2 + df['GC']*-3.0 + df['CV']*-3.0 + \
                    df['CA']*-1.0 + df['GS']*-1.0 + df['FC']*-0.3 + df['PC']*-1.0
                    
df['scout_total'] = df['G']*8.0 + df['A']*5.0 + df['FT']*3.0 + df['FD']*1.2 + \
                    df['FF']*0.8 + df['FS']*0.5 + df['PS']*1.0 + df['PP']*-4.0 + \
                    df['I']*-0.1 + df['SG']*5.0 + df['DP']*7.0 + \
                    df['DE']*1.0 + df['DS']*1.2 + df['GC']*-3.0 + df['CV']*-3.0 + \
                    df['CA']*-1.0 + df['GS']*-1.0 + df['FC']*-0.3 + df['PC']*-1.0

In [132]:
df.head()

,rodada_id,pontos_num,preco_num,variacao_num,media_num,jogos_num,minimo_para_valorizar,apelido,clube_id,clube,...,PC,CV,GC,DP,PP,clube_adversario_id,clube_adversario,scout_ataque,scout_defesa,scout_total
0,1,0.0,4.53,-0.62,2.53,6,0.18,Alisson,276,SAO,...,0.0,0.0,0.0,0.0,0.0,263,BOT,-0.1,0.0,-0.1
1,2,0.0,4.53,-0.62,2.53,6,0.18,Alisson,276,SAO,...,0.0,0.0,0.0,0.0,0.0,327,AME,5.8,0.0,5.8
2,3,0.0,4.53,-0.62,2.53,6,0.18,Alisson,276,SAO,...,0.0,0.0,0.0,0.0,0.0,294,CFC,3.5,1.8,5.3
3,4,0.0,4.53,-0.62,2.53,6,0.18,Alisson,276,SAO,...,0.0,0.0,0.0,0.0,0.0,285,INT,0.0,0.9,0.9
4,5,0.0,4.53,-0.62,2.53,6,0.18,Alisson,276,SAO,...,0.0,0.0,0.0,0.0,0.0,356,FOR,1.3,2.0,3.3

In [133]:
df.shape

(2000, 36)

In [134]:
df.describe()

,rodada_id,pontos_num,preco_num,variacao_num,media_num,jogos_num,minimo_para_valorizar,clube_id,DS,FC,...,PS,PC,CV,GC,DP,PP,clube_adversario_id,scout_ataque,scout_defesa,scout_total
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000
mean,3.508000,2.980655,6.779665,0.025880,3.516785,4.721500,2.535180,335.213000,0.995500,0.886000,...,0.007000,0.008000,0.008500,0.002000,0.001000,0.002000,339.243000,1.92295,1.287800,3.210750
std,1.708624,3.705451,3.663298,0.766225,2.296220,1.418077,2.203328,232.417733,1.309327,1.120996,...,0.083394,0.089107,0.091826,0.044688,0.031615,0.044688,240.272034,3.15714,2.339837,3.788041
min,1.000000,-3.000000,0.660000,-2.960000,-1.600000,0.000000,-1.400000,262.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,262.000000,-0.20000,-4.200000,-4.200000
25%,2.000000,0.000000,3.920000,-0.320000,1.740000,4.000000,0.860000,266.750000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,267.000000,0.00000,0.000000,0.400000
50%,4.000000,1.700000,6.235000,0.000000,3.580000,5.000000,2.080000,280.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,282.000000,0.80000,0.600000,2.000000
75%,5.000000,4.900000,8.950000,0.250000,4.960000,6.000000,3.760000,290.000000,2.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,293.000000,2.00000,2.100000,5.000000
max,6.000000,16.800000,20.860000,3.030000,15.300000,6.000000,11.350000,1371.000000,9.000000,7.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1371.000000,25.20000,15.500000,27.600000

### PontuaÃ§Ã£o por clube

In [135]:
df[['clube','scout_total','scout_ataque','scout_defesa']].groupby(by='clube').sum().sort_values('scout_total',ascending=False)

       scout_total  scout_ataque  scout_defesa
clube
CRU          432.7         233.0         199.7
FLU          427.0         237.8         189.2
PAL          401.9         300.0         101.9
FOR          399.0         205.6         193.4
BOT          390.3         226.5         163.8
CAM          387.1         200.3         186.8
SAN          385.4         183.6         201.8
FLA          381.6         243.2         138.4
SAO          351.4         175.2         176.2
CAP          329.4         212.5         116.9
GRE          326.5         161.4         165.1
BAH          297.9         196.4         101.5
INT          280.4         140.9         139.5
VAS          253.6         155.3          98.3
BGT          246.4         198.4          48.0
CFC          244.1         155.0          89.1
GOI          233.4         172.6          60.8
CUI          218.7         134.2          84.5
AME          217.7         169.0          48.7
COR          217.0         145.0          72.0

### ValorizaÃ§Ã£o

In [136]:
df[['apelido','clube','posicao','minimo_para_valorizar']].query('clube == "PAL"').sort_values('minimo_para_valorizar',ascending=True).drop_duplicates().head(60)

             apelido clube posicao  minimo_para_valorizar
308        Jhon Jhon   PAL     mei                  -0.07
871      Breno Lopes   PAL     ata                   0.17
876      Flaco LÃ³pez   PAL     ata                   0.34
873     Bruno Tabata   PAL     mei                   0.46
374   Luis Guilherme   PAL     mei                   0.76
715         Weverton   PAL     gol                   1.26
236     Richard RÃ­os   PAL     mei                   1.27
683             Dudu   PAL     ata                   1.49
844             Rony   PAL     ata                   1.55
833            Mayke   PAL     lat                   1.58
868        Vanderlan   PAL     lat                   1.88
838             Luan   PAL     zag                   2.26
859          Endrick   PAL     ata                   2.29
865          Fabinho   PAL     mei                   2.62
854   Gabriel Menino   PAL     mei                   3.25
881   Rafael Navarro   PAL     ata                   3.26
723    Abel Ferreira   PAL     tec                   3.30
878          Giovani   PAL     ata                   3.38
841        ZÃ© Rafael   PAL     mei                   3.38
851         Piquerez   PAL     lat                   3.80
1415   Raphael Veiga   PAL     mei                   3.99
884   Gustavo Garcia   PAL     lat                   4.07
733    Gustavo GÃ³mez   PAL     zag                   4.69
447     Marcos Rocha   PAL     lat                   7.07
469            Artur   PAL     ata                   7.32
816           Murilo   PAL     zag                  11.35

In [137]:
df[['apelido','clube','posicao','variacao_num']].sort_values('variacao_num',ascending=False).drop_duplicates().head(20)

               apelido clube posicao  variacao_num
594           Gilberto   CRU     ata          3.03
1021             Pablo   CAP     ata          2.49
640               Nino   FLU     zag          2.44
1054             Erick   CAP     mei          2.36
680         David Luiz   FLA     zag          2.15
1688          Thaciano   BAH     mei          2.11
99              Marlon   CRU     lat          2.11
1142           Zaracho   CAM     mei          2.04
1003    Matheus FranÃ§a   FLA     mei          1.96
701         JoÃ£o Paulo   SAN     gol          1.95
1084            Vargas   CAM     ata          1.95
415   Henrique Dourado   CRU     ata          1.92
1713    Gabriel Grando   GRE     gol          1.85
1504           William   CRU     lat          1.79
1952        Bruno Melo   GOI     zag          1.78
1444            Robson   CFC     ata          1.77
541               Biel   BAH     ata          1.76
217               Pepa   CRU     tec          1.73
473              Artur   PAL     ata          1.73
1562      Igor Formiga   CRU     lat          1.67

### FunÃ§Ã£o de AnÃ¡lise Clube e Jogador

In [138]:
def anl_scout(scout,n):
  anl_clube = df[['clube','posicao',scout]].groupby(by=['clube','posicao']).sum().sort_values(scout,ascending=False).head(n)
  print('========= AnÃ¡lise Clube Total =========')
  print(anl_clube)
  #anl_clube = df[['clube','posicao',scout]].groupby(by=['clube','posicao']).sum().sort_values(scout,ascending=False).apply(lambda x: x / atual_rodada).head(n)
  #print('\n')
  #print('========= AnÃ¡lise Clube MÃ©dia =========')
  #print(anl_clube)
  anl_jogador = df[['apelido','clube','posicao',scout]].groupby(by=['apelido','clube','posicao']).sum().sort_values(scout,ascending=False).head(n)
  print('\n')
  print('========= AnÃ¡lise Jogador Total =========')
  print(anl_jogador)  
  #anl_jogador = df[['apelido','clube','posicao',scout]].groupby(by=['apelido','clube','posicao']).sum().sort_values(scout,ascending=False).apply(lambda x: x / atual_rodada).head(n)
  #print('\n')
  #print('========= AnÃ¡lise Jogador MÃ©dia =========')
  #print(anl_jogador)  
  filtro_apelido = anl_jogador.index.get_level_values('apelido')
  filtro_clube = anl_jogador.index.get_level_values('clube')
  anl_jogador_val = df[['apelido','clube','posicao','minimo_para_valorizar']].query('apelido in (@filtro_apelido) and clube in (@filtro_clube)').drop_duplicates()
  print('\n')
  print('========= AnÃ¡lise ValorizaÃ§Ã£o =========')
  print('\n')
  print(anl_jogador_val)

### Ataque

In [139]:
df['FIN'] = df['FT'] + df['FD'] + df['FF']
df['ATA'] = df['FT'] + df['FD'] + df['FF'] + df['G'] + df['A']

Artilheiros

In [158]:
anl_scout('G',3)

========= AnÃ¡lise Clube Total =========
                 G
clube posicao
BOT   ata      9.0
CRU   ata      8.0
PAL   ata      8.0


========= AnÃ¡lise Jogador Total =========
                                 G
apelido         clube posicao
Tiquinho Soares BOT   ata      6.0
Raphael Veiga   PAL   mei      4.0
RÃ³ger Guedes    COR   ata      3.0


========= AnÃ¡lise ValorizaÃ§Ã£o =========


              apelido clube posicao  minimo_para_valorizar
570   Tiquinho Soares   BOT     ata                   7.41
587      RÃ³ger Guedes   COR     ata                   6.12
1415    Raphael Veiga   PAL     mei                   3.99

Lideres em AssitÃªncia

In [141]:
anl_scout('A',7)

========= AnÃ¡lise Clube Total =========
                 A
clube posicao
CAM   ata      5.0
CRU   mei      5.0
PAL   mei      4.0
SAN   ata      4.0
CAP   ata      4.0
PAL   lat      4.0
BAH   mei      4.0


========= AnÃ¡lise Jogador Total =========
                             A
apelido     clube posicao
PavÃ³n       CAM   ata      3.0
Ganso       FLU   mei      3.0
Machado     CRU   mei      3.0
Dudu        PAL   ata      2.0
Fausto Vera COR   mei      2.0
Cauly       BAH   mei      2.0
Thaciano    BAH   mei      2.0


========= AnÃ¡lise ValorizaÃ§Ã£o =========


          apelido clube posicao  minimo_para_valorizar
641         Ganso   FLU     mei                   7.72
681          Dudu   PAL     ata                   1.49
1121        PavÃ³n   CAM     ata                   4.21
1155        Cauly   BAH     mei                   1.23
1380  Fausto Vera   COR     mei                   1.63
1544      Machado   CRU     mei                   5.28
1686     Thaciano   BAH     mei                   7.31

Maiores Finalizadores

In [142]:
anl_scout('FIN',7)

========= AnÃ¡lise Clube Total =========
                FIN
clube posicao
CRU   ata      39.0
PAL   ata      35.0
AME   ata      33.0
CAM   ata      33.0
BAH   mei      32.0
FOR   mei      32.0
PAL   mei      31.0


========= AnÃ¡lise Jogador Total =========
                                FIN
apelido         clube posicao
Bruno Rodrigues CRU   ata      17.0
Hulk            CAM   ata      16.0
RÃ³ger Guedes    COR   ata      15.0
Cano            FLU   ata      14.0
Gilberto        CRU   ata      13.0
Thaciano        BAH   mei      13.0
Luis SuÃ¡rez     GRE   ata      12.0


========= AnÃ¡lise ValorizaÃ§Ã£o =========


              apelido clube posicao  minimo_para_valorizar
510              Hulk   CAM     ata                   4.26
587      RÃ³ger Guedes   COR     ata                   6.12
593          Gilberto   CRU     ata                   8.96
1419      Luis SuÃ¡rez   GRE     ata                   2.94
1424             Cano   FLU     ata                   2.28
1525  Bruno Rodrigues   CRU     ata                   4.87
1686         Thaciano   BAH     mei                   7.31

Melhores Atacantes

In [143]:
anl_scout('ATA',7)

========= AnÃ¡lise Clube Total =========
                ATA
clube posicao
CRU   ata      48.0
CAM   ata      45.0
PAL   ata      45.0
AME   ata      39.0
PAL   mei      39.0
FLA   ata      38.0
BAH   mei      37.0


========= AnÃ¡lise Jogador Total =========
                                ATA
apelido         clube posicao
Hulk            CAM   ata      21.0
Bruno Rodrigues CRU   ata      20.0
Raphael Veiga   PAL   mei      18.0
RÃ³ger Guedes    COR   ata      18.0
Cano            FLU   ata      16.0
Gilberto        CRU   ata      16.0
Thaciano        BAH   mei      16.0


========= AnÃ¡lise ValorizaÃ§Ã£o =========


              apelido clube posicao  minimo_para_valorizar
510              Hulk   CAM     ata                   4.26
587      RÃ³ger Guedes   COR     ata                   6.12
593          Gilberto   CRU     ata                   8.96
1415    Raphael Veiga   PAL     mei                   3.99
1424             Cano   FLU     ata                   2.28
1525  Bruno Rodrigues   CRU     ata                   4.87
1686         Thaciano   BAH     mei                   7.31

Mais Sofrem Faltas

In [144]:
anl_scout('FS',7)

========= AnÃ¡lise Clube Total =========
                 FS
clube posicao
GOI   mei      64.0
FLU   mei      57.0
BAH   ata      52.0
GRE   mei      51.0
VAS   mei      45.0
SAN   ata      44.0
PAL   mei      41.0


========= AnÃ¡lise Jogador Total =========
                              FS
apelido      clube posicao
Jair         VAS   mei      22.0
RÃ³ger Guedes COR   ata      21.0
Kaio CÃ©sar   CFC   ata      19.0
Ademir       BAH   ata      19.0
Diego        GOI   mei      19.0
Bitello      GRE   mei      18.0
Sander       GOI   lat      17.0


========= AnÃ¡lise ValorizaÃ§Ã£o =========


           apelido clube posicao  minimo_para_valorizar
107           Jair   VAS     mei                   3.80
587   RÃ³ger Guedes   COR     ata                   6.12
823         Sander   GOI     lat                   2.45
1131        Ademir   BAH     ata                   5.00
1505    Kaio CÃ©sar   CFC     ata                   0.42
1730       Bitello   GRE     mei                   2.87
1973         Diego   GOI     mei                   3.76

### Defesa

In [145]:
df['PEG'] = df['DP'] + df['DE'] - df['GS']
df['DEF'] = df['DS'] - df['CA'] - df['CV'] - df['FC']

Melhor Defesa

In [146]:
anl_scout('DEF',7)

========= AnÃ¡lise Clube Total =========
                DEF
clube posicao
CRU   lat      27.0
GRE   mei      17.0
FOR   mei      17.0
BOT   lat      16.0
INT   lat      15.0
SAN   lat      13.0
CFC   lat      13.0


========= AnÃ¡lise Jogador Total =========
                                  DEF
apelido           clube posicao
Marlon            CRU   lat      24.0
Rubens            CAM   lat      12.0
Matheus Fernandes BGT   mei      12.0
Tinga             FOR   lat      10.0
Cristaldo         GRE   mei      10.0
RenÃª              INT   lat      10.0
Matheus Alexandre CUI   lat      10.0


========= AnÃ¡lise ValorizaÃ§Ã£o =========


                apelido clube posicao  minimo_para_valorizar
99               Marlon   CRU     lat                   9.52
687                RenÃª   INT     lat                   3.38
1282             Rubens   CAM     lat                   4.95
1309  Matheus Fernandes   BGT     mei                   4.02
1400              Tinga   FOR     lat                   6.71
1611  Matheus Alexandre   CUI     lat                   4.25
1691          Cristaldo   GRE     mei                   2.80

Maior LadrÃ£o de bolas

In [147]:
anl_scout('DS',7)

========= AnÃ¡lise Clube Total =========
                 DS
clube posicao
SAN   mei      56.0
FOR   mei      56.0
GRE   mei      56.0
SAO   mei      50.0
VAS   mei      49.0
COR   mei      49.0
CAM   mei      48.0


========= AnÃ¡lise Jogador Total =========
                                   DS
apelido           clube posicao
Marlon            CRU   lat      31.0
Matheus Fernandes BGT   mei      22.0
Rubens            CAM   lat      22.0
Natanael          CFC   lat      21.0
Sander            GOI   lat      16.0
Caio Alexandre    FOR   mei      16.0
Puma RodrÃ­guez    VAS   lat      16.0


========= AnÃ¡lise ValorizaÃ§Ã£o =========


                apelido clube posicao  minimo_para_valorizar
99               Marlon   CRU     lat                   9.52
128      Puma RodrÃ­guez   VAS     lat                   2.43
823              Sander   GOI     lat                   2.45
1282             Rubens   CAM     lat                   4.95
1309  Matheus Fernandes   BGT     mei                   4.02
1482           Natanael   CFC     lat                   5.27
1906     Caio Alexandre   FOR     mei                   3.11

Melhor Goleiro

In [148]:
anl_scout('PEG',7)

========= AnÃ¡lise Clube Total =========
                PEG
clube posicao
VAS   gol      26.0
FOR   gol      23.0
BOT   gol      22.0
SAN   gol      22.0
GRE   gol      21.0
CRU   gol      20.0
FLU   gol      20.0


========= AnÃ¡lise Jogador Total =========
                               PEG
apelido        clube posicao
LÃ©o Jardim     VAS   gol      26.0
Lucas Perri    BOT   gol      22.0
JoÃ£o Paulo     SAN   gol      22.0
FÃ¡bio          FLU   gol      20.0
Rafael Cabral  CRU   gol      20.0
Gabriel Grando GRE   gol      17.0
Rafael         SAO   gol      17.0


========= AnÃ¡lise ValorizaÃ§Ã£o =========


             apelido clube posicao  minimo_para_valorizar
12            Rafael   SAO     gol                   0.82
122       LÃ©o Jardim   VAS     gol                  -0.02
605    Rafael Cabral   CRU     gol                   4.82
698       JoÃ£o Paulo   SAN     gol                   8.30
1233          Rafael   BOT     lat                   0.86
1271     Lucas Perri   BOT     gol                   0.35
1646           FÃ¡bio   FLU     gol                   4.34
1659           FÃ¡bio   GRE     lat                   6.10
1713  Gabriel Grando   GRE     gol                   5.55

## EscalaÃ§Ã£o

In [149]:
df_rodada_clube_casa = df_rodadas_full.query('rodada_id == @atual_rodada+1').rename(columns={'clube_casa': 'clube','clube_visitante': 'clube_adversario'})[['clube','clube_adversario']]
df_rodada_clube_visi = df_rodadas_full.query('rodada_id == @atual_rodada+1').rename(columns={'clube_visitante': 'clube','clube_casa': 'clube_adversario'})[['clube','clube_adversario']]

In [150]:
def anl_jogadoes(filtro_apelido,posicao,analise):
  df_escalacao = df[['apelido','clube','posicao','minimo_para_valorizar']].query('apelido in (@filtro_apelido)').drop_duplicates()
  if analise in ('ataque', 'meio'):
    df_anl_jogador = df[['apelido','clube','posicao','ATA','FIN','G','A','DS','FS']].groupby(by=['apelido','clube','posicao']).sum().reset_index()
    df_escalacao = pd.merge(df_escalacao, df_anl_jogador,  how='left', left_on=['apelido','clube','posicao'], right_on = ['apelido','clube','posicao'])
  elif analise in ('lateral', 'zaga'):
    df_anl_jogador = df[['apelido','clube','posicao','DEF','FIN','G','A','DS','FS','FC','CA','CV']].groupby(by=['apelido','clube','posicao']).sum().reset_index()
    df_escalacao = pd.merge(df_escalacao, df_anl_jogador,  how='left', left_on=['apelido','clube','posicao'], right_on = ['apelido','clube','posicao'])
  else:
    df_anl_jogador = df[['apelido','clube','posicao','PEG','DP','DE','GS','FS','CA','CV']].groupby(by=['apelido','clube','posicao']).sum().reset_index()
    df_escalacao = pd.merge(df_escalacao, df_anl_jogador,  how='left', left_on=['apelido','clube','posicao'], right_on = ['apelido','clube','posicao'])
  df_escalacao = pd.merge(df_escalacao, df_rodada_clube_casa,  how='left', left_on=['clube'], right_on = ['clube'])
  df_escalacao = pd.merge(df_escalacao, df_rodada_clube_visi,  how='left', left_on=['clube'], right_on = ['clube'])
  df_escalacao['clube_adversario'] = df_escalacao.clube_adversario_x.combine_first(df_escalacao.clube_adversario_y)
  df_escalacao.drop(columns=['clube_adversario_x','clube_adversario_y'],inplace=True)
  df_group_clube = df[['clube','G','DS']].groupby(by='clube').sum().rename(columns={'G': 'Gols Marcados','DS': 'Desarmes Feitos'})
  df_group_adversario =df[['clube_adversario','G','DS']].groupby(by='clube_adversario').sum().rename(columns={'G': 'Gols Sofridos','DS': 'Bolas Perdidas'})
  df_escalacao = pd.merge(df_escalacao, df_group_clube,  how='left', left_on=['clube_adversario'], right_on = ['clube'])
  df_escalacao = pd.merge(df_escalacao, df_group_adversario,  how='left', left_on=['clube_adversario'], right_on = ['clube_adversario'])
  if analise in ('ataque', 'meio'):
    return df_escalacao.query('posicao == @posicao').sort_values('ATA',ascending=False).reset_index(drop=True)
  elif analise in ('lateral', 'zaga'):
    return df_escalacao.query('posicao == @posicao').sort_values('DEF',ascending=False).reset_index(drop=True)   
  else:
    return df_escalacao.query('posicao == @posicao').sort_values('PEG',ascending=False).reset_index(drop=True)

In [151]:
def get_filtro_apelido(scout,n,posicao):
  df_filtro_apelido = df[['apelido','clube','posicao',scout]].query('posicao == @posicao').groupby(by=['apelido','clube','posicao']).sum().sort_values(scout,ascending=False).head(n)
  return df_filtro_apelido.index.get_level_values('apelido')

### Ataque

In [152]:
filtro_apelido = get_filtro_apelido('ATA',10,'ata')
anl_jogadoes(filtro_apelido,'ata','ataque')

,apelido,clube,posicao,minimo_para_valorizar,ATA,FIN,G,A,DS,FS,clube_adversario,Gols Marcados,Desarmes Feitos,Gols Sofridos,Bolas Perdidas
0,Hulk,CAM,ata,4.26,21.0,16.0,3.0,2.0,0.0,15.0,CFC,5.0,111.0,13.0,105.0
1,Bruno Rodrigues,CRU,ata,4.87,20.0,17.0,2.0,1.0,4.0,10.0,CUI,4.0,108.0,12.0,82.0
2,RÃ³ger Guedes,COR,ata,6.12,18.0,15.0,3.0,0.0,2.0,21.0,FLA,12.0,95.0,9.0,118.0
3,Gilberto,CRU,ata,8.96,16.0,13.0,3.0,0.0,3.0,4.0,CUI,4.0,108.0,12.0,82.0
4,Cano,FLU,ata,2.28,16.0,14.0,2.0,0.0,4.0,1.0,BOT,13.0,110.0,6.0,93.0
5,Tiquinho Soares,BOT,ata,7.41,14.0,6.0,6.0,2.0,4.0,9.0,FLU,12.0,74.0,5.0,99.0
6,Dudu,PAL,ata,1.49,14.0,11.0,1.0,2.0,3.0,10.0,SAN,8.0,124.0,5.0,111.0
7,AloÃ­sio,AME,ata,1.49,14.0,10.0,3.0,1.0,1.0,3.0,FOR,9.0,106.0,4.0,95.0
8,Everton,FLA,ata,3.72,14.0,12.0,0.0,2.0,6.0,4.0,COR,5.0,92.0,11.0,95.0
9,Gabriel,FLA,ata,6.31,14.0,11.0,3.0,0.0,0.0,6.0,COR,5.0,92.0,11.0,95.0

### Meio

In [153]:
filtro_apelido = get_filtro_apelido('ATA',10,'mei')
anl_jogadoes(filtro_apelido,'mei','meio')

,apelido,clube,posicao,minimo_para_valorizar,ATA,FIN,G,A,DS,FS,clube_adversario,Gols Marcados,Desarmes Feitos,Gols Sofridos,Bolas Perdidas
0,Raphael Veiga,PAL,mei,3.99,18.0,12.0,4.0,2.0,5.0,8.0,SAN,8.0,124.0,5.0,111.0
1,Thaciano,BAH,mei,7.31,16.0,13.0,1.0,2.0,6.0,8.0,GOI,5.0,92.0,11.0,85.0
2,Hyoran,CAM,mei,3.95,12.0,11.0,1.0,0.0,5.0,4.0,CFC,5.0,111.0,13.0,105.0
3,Cauly,BAH,mei,1.23,12.0,10.0,0.0,2.0,3.0,4.0,GOI,5.0,92.0,11.0,85.0
4,Lima,FLU,mei,3.56,11.0,8.0,2.0,1.0,10.0,12.0,BOT,13.0,110.0,6.0,93.0
5,Calebe,FOR,mei,2.44,11.0,11.0,0.0,0.0,5.0,12.0,AME,5.0,68.0,16.0,91.0
6,Gabriel Menino,PAL,mei,3.25,10.0,9.0,0.0,1.0,9.0,9.0,SAN,8.0,124.0,5.0,111.0
7,Matheus FranÃ§a,FLA,mei,6.26,10.0,9.0,1.0,0.0,6.0,4.0,COR,5.0,92.0,11.0,95.0
8,Erick,CAP,mei,7.00,10.0,8.0,1.0,1.0,7.0,3.0,BGT,9.0,90.0,11.0,108.0
9,Mateus Vital,CRU,mei,4.18,10.0,9.0,0.0,1.0,6.0,7.0,CUI,4.0,108.0,12.0,82.0

### Lateral

In [154]:
filtro_apelido = get_filtro_apelido('ATA',10,'lat')
anl_jogadoes(filtro_apelido,'lat','lateral')

,apelido,clube,posicao,minimo_para_valorizar,DEF,FIN,G,A,DS,FS,FC,CA,CV,clube_adversario,Gols Marcados,Desarmes Feitos,Gols Sofridos,Bolas Perdidas
0,Rubens,CAM,lat,4.95,12.0,4.0,0.0,0.0,22.0,4.0,9.0,1.0,0.0,CFC,5.0,111.0,13.0,105.0
1,Sander,GOI,lat,2.45,9.0,3.0,0.0,1.0,16.0,17.0,7.0,0.0,0.0,BAH,7.0,100.0,11.0,120.0
2,Puma RodrÃ­guez,VAS,lat,2.43,7.0,6.0,0.0,0.0,16.0,5.0,8.0,1.0,0.0,SAO,8.0,99.0,4.0,120.0
3,Natanael,CFC,lat,5.27,7.0,7.0,0.0,0.0,21.0,8.0,13.0,1.0,0.0,CAM,9.0,107.0,5.0,104.0
4,Fagner,COR,lat,2.06,6.0,4.0,0.0,0.0,12.0,7.0,4.0,2.0,0.0,FLA,12.0,95.0,9.0,118.0
5,Marcelo,FLU,lat,5.08,1.0,4.0,0.0,0.0,3.0,9.0,1.0,1.0,0.0,BOT,13.0,110.0,6.0,93.0
6,Caio Paulista,SAO,lat,0.55,0.0,4.0,0.0,1.0,6.0,10.0,5.0,1.0,0.0,VAS,6.0,100.0,7.0,98.0
7,Ayrton Lucas,FLA,lat,1.51,-4.0,5.0,1.0,0.0,8.0,9.0,11.0,1.0,0.0,COR,5.0,92.0,11.0,95.0
8,Bruno Pacheco,FOR,lat,4.63,-4.0,6.0,0.0,1.0,9.0,6.0,12.0,1.0,0.0,AME,5.0,68.0,16.0,91.0
9,Juninho Capixaba,BGT,lat,4.79,-6.0,5.0,1.0,1.0,11.0,5.0,14.0,3.0,0.0,CAP,10.0,81.0,7.0,78.0

### Zaga

In [155]:
filtro_apelido = get_filtro_apelido('ATA',10,'zag')
anl_jogadoes(filtro_apelido,'zag','zaga')

,apelido,clube,posicao,minimo_para_valorizar,DEF,FIN,G,A,DS,FS,FC,CA,CV,clube_adversario,Gols Marcados,Desarmes Feitos,Gols Sofridos,Bolas Perdidas
0,Nino,FLU,zag,9.37,1.0,4.0,2.0,0.0,4.0,7.0,3.0,0.0,0.0,BOT,13.0,110.0,6.0,93.0
1,Danilo Avelar,AME,zag,2.24,0.0,3.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,FOR,9.0,106.0,4.0,95.0
2,Marllon,CUI,zag,0.90,0.0,2.0,1.0,1.0,6.0,4.0,4.0,2.0,0.0,CRU,11.0,117.0,5.0,83.0
3,Luan,PAL,zag,2.26,-1.0,2.0,1.0,0.0,4.0,2.0,5.0,0.0,0.0,SAN,8.0,124.0,5.0,111.0
4,Eduardo Bauermann,SAN,zag,6.52,-2.0,5.0,1.0,0.0,2.0,0.0,3.0,0.0,1.0,PAL,15.0,98.0,5.0,95.0
5,BrÃ­tez,FOR,zag,2.91,-2.0,2.0,0.0,1.0,7.0,4.0,6.0,2.0,1.0,AME,5.0,68.0,16.0,91.0
6,Bruno Melo,GOI,zag,5.46,-2.0,4.0,1.0,0.0,4.0,4.0,3.0,3.0,0.0,BAH,7.0,100.0,11.0,120.0
7,David Luiz,FLA,zag,7.47,-4.0,2.0,1.0,1.0,2.0,0.0,5.0,1.0,0.0,COR,5.0,92.0,11.0,95.0
8,Mauricio Lemos,CAM,zag,5.50,-4.0,2.0,1.0,0.0,5.0,4.0,6.0,3.0,0.0,CFC,5.0,111.0,13.0,105.0
9,Eduardo Santos,BGT,zag,0.42,-5.0,2.0,0.0,1.0,2.0,2.0,6.0,1.0,0.0,CAP,10.0,81.0,7.0,78.0

### Goleiro

In [156]:
filtro_apelido = get_filtro_apelido('ATA',10,'gol')
anl_jogadoes(filtro_apelido,'gol','goleiro')

,apelido,clube,posicao,minimo_para_valorizar,PEG,DP,DE,GS,FS,CA,CV,clube_adversario,Gols Marcados,Desarmes Feitos,Gols Sofridos,Bolas Perdidas
0,LÃ©o Jardim,VAS,gol,-0.02,26.0,0.0,33.0,7.0,0.0,1.0,0.0,SAO,8.0,99.0,4.0,120.0
1,Rafael Cabral,CRU,gol,4.82,20.0,0.0,25.0,5.0,1.0,0.0,0.0,CUI,4.0,108.0,12.0,82.0
2,Rafael,SAO,gol,0.82,17.0,0.0,21.0,4.0,0.0,0.0,0.0,VAS,6.0,100.0,7.0,98.0
3,Bento,CAP,gol,-0.07,9.0,0.0,16.0,7.0,1.0,1.0,0.0,BGT,9.0,90.0,11.0,108.0
4,Matheus Cunha,FLA,gol,0.73,7.0,0.0,8.0,1.0,0.0,0.0,0.0,COR,5.0,92.0,11.0,95.0
5,Tadeu,GOI,gol,6.23,6.0,0.0,10.0,4.0,1.0,0.0,0.0,BAH,7.0,100.0,11.0,120.0
6,Santos,FLA,gol,1.50,6.0,0.0,14.0,8.0,1.0,0.0,0.0,COR,5.0,92.0,11.0,95.0
7,Adriel,GRE,gol,10.94,4.0,0.0,4.0,0.0,0.0,0.0,0.0,INT,4.0,111.0,8.0,101.0
8,Walter,CUI,gol,-1.38,3.0,0.0,15.0,12.0,0.0,1.0,0.0,CRU,11.0,117.0,5.0,83.0
9,MaurÃ­cio Kozlinski,FOR,gol,5.56,1.0,0.0,1.0,0.0,0.0,0.0,0.0,AME,5.0,68.0,16.0,91.0